CREATE TABLE locations(
    sid INT NOT NULL UNIQUE PRIMARY KEY,
    id BIGINT,
    name VARCHAR(1000),
    street VARCHAR(255),
    zip VARCHAR(255),
    city VARCHAR(255),
    region VARCHAR(255),
    cd VARCHAR(2),
    aj_exact_city_match BOOLEAN,
    aj_exact_country_match BOOLEAN,
    blurb VARCHAR(1000),
    dir_city_id VARCHAR(255),
    dir_city_name VARCHAR(255),
    dir_city_slug VARCHAR(255),
    dir_country_id VARCHAR(255),
    dir_country_name VARCHAR(255),
    lat FLOAT,
    lng FLOAT,
    primary_alias_on_fb VARCHAR(255),
    slug VARCHAR(255),
    website VARCHAR(255),
    cts DATETIME2
)